"""Init

Revision ID: 3c85dd9199b7
Revises: 
Create Date: 2023-02-10 15:29:29.524012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c85dd9199b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('renter',
    sa.Column('account', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renter_account'), 'renter', ['account'], unique=True)
    op.create_index(op.f('ix_renter_id'), 'renter', ['id'], unique=False)
    op.create_table('service_type',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mesure', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_type_id'), 'service_type', ['id'], unique=False)
    op.create_table('apartment',
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('house', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('resedents', sa.Integer(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['renter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_index(op.f('ix_apartment_id'), 'apartment', ['id'], unique=False)
    op.create_table('service',
    sa.Column('service_number', sa.Integer(), nullable=True),
    sa.Column('tariff', sa.Float(), nullable=True),
    sa.Column('service_type_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    op.create_table('payment',
    sa.Column('actualy_spent', sa.Float(), nullable=True),
    sa.Column('border_date', sa.DateTime(), nullable=True),
    sa.Column('payed_in_time', sa.Boolean(), nullable=True),
    sa.Column('date_of_payment', sa.DateTime(), nullable=True),
    sa.Column('renter_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['renter_id'], ['renter.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_apartment_id'), table_name='apartment')
    op.drop_table('apartment')
    op.drop_index(op.f('ix_service_type_id'), table_name='service_type')
    op.drop_table('service_type')
    op.drop_index(op.f('ix_renter_id'), table_name='renter')
    op.drop_index(op.f('ix_renter_account'), table_name='renter')
    op.drop_table('renter')
    # ### end Alembic commands ###
